name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      - name: Build core app
        run: msbuild .\src\JiuLing.AutoUpgrade\JiuLing.AutoUpgrade.csproj /P:Configuration=Release

      - name: Setup .NET 6
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
          
      - name: Restore dependencies
        run: dotnet restore
        
      - name: Build shell app
        run: dotnet build .\src\JiuLing.AutoUpgrade.Shell\JiuLing.AutoUpgrade.Shell.csproj --no-restore -c release

      - name: Get version
        uses: olegtarasov/get-tag@v2.1
        id: tagName

      - name: Create zip
        shell: pwsh
        # 配置【编译后的文件地址】
        run: Compress-Archive -Path .\src\JiuLing.AutoUpgrade.Shell\bin\Release\* -DestinationPath .\src\JiuLing.AutoUpgrade.Shell\bin\Release\JiuLing.AutoUpgrade.Shell_${{ steps.tagName.outputs.tag }}.zip

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          # 配置【README地址】
          body: |
            Release为自动生成，具体内容请查看提交日志，或直接查看[README](https://github.com/JiuLing-zhang/JiuLing.AutoUpgrade#readme)
          # 配置【zip文件地址】
          files: .\src\JiuLing.AutoUpgrade.Shell\bin\Release\JiuLing.AutoUpgrade.Shell_${{ steps.tagName.outputs.tag }}.zip

      #配置发布NuGet
      - name: Publish  
        uses: brandedoutcast/publish-nuget@v2.5.2  
        with:   
          PROJECT_FILE_PATH: src/JiuLing.AutoUpgrade.Shell/JiuLing.AutoUpgrade.Shell.csproj        
          PACKAGE_NAME: JiuLing.AutoUpgrade
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}  
          TAG_COMMIT: false
